version: "3.8"

services:
  frontend:
    build:
      context: ./pj-lms-front # Dockerfile의 경로
      dockerfile: Dockerfile.front
    container_name: dev_code_lab_front
    ports:
      - "80:3000"
    volumes:
      - ./pj-lms-front/nginx.conf:/etc/nginx/nginx.conf
      - ./pj-lms-front/build:/app/build
    command: ["nginx", "-g", "daemon off;"]

  backend:
    # image: openjdk:17-jdk-alpin
    build:
      context: ./pj-lms-back # Dockerfile의 경로
      dockerfile: Dockerfile.back
    container_name: dev_code_lab_back
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    volumes:
      - ./pj-lms-back/lms-0.0.1-SNAPSHOT.jar:/app/lms-0.0.1-SNAPSHOT.jar
    command: ["java", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "-jar", "/app/lms-0.0.1-SNAPSHOT.jar"]
