version: "3.8"

services:
  frontend:
    build:
      context: ./pj-lms-front # Dockerfile의 경로
      dockerfile: Dockerfile.front
    container_name: dev_code_lab_front
    ports:
      - "80:3000"
    volumes:
      - ./pj-lms-front/nginx.conf:/etc/nginx/nginx.conf
      - ./pj-lms-front/build:/app/build
    command: ["nginx", "-g", "daemon off;"]
